# Inference
#    plot_rgb: false
#    damping: high damping
#    max_spring_force_magnitude: 50
# Data collection:
#    plot_rgb: true
#    damping: low damping
#    max_spring_force_magnitude: 15
# always check the first few parameters:
data_folder: "/home/yifanhou/data/raw/umift_debug"
mock_hardware: false
bimanual: false
use_perturbation_generator: false

run_robot_thread: true
run_wrench_thread: true
run_rgb_thread: false
run_eoat_thread: false
plot_rgb: false

rgb_buffer_size: 11
robot_buffer_size: 100
eoat_buffer_size: 20
wrench_buffer_size: 360
camera_selection: "GOPRO"
force_sensing_mode: "FORCE_MODE_COINFT"
low_damping: [2.0, 2.0, 2.0, 0.1, 0.1, 0.1]
output_rgb_hw: [202, 270]
wrench_filter_parameters: [5, 0.000143, 5] # cutoff frequency, sampling time, order
check_robot_loop_overrun: false


ur_rtde0:
  robot_ip: "192.168.2.106"
  rtde_frequency: 500.0
  rt_receive_priority: 90
  rt_control_priority: 85
  interface_priority: 80
  linear_vel: 0.5
  linear_acc: 0.5
  servoL_lookahead_time: 0.1
  servoL_gain: 600
  robot_interface_config:
    zone_safety_mode: "SAFETY_MODE_TRUNCATE"
    incre_safety_mode: "SAFETY_MODE_STOP"
    operation_mode: "OPERATION_MODE_CARTESIAN"
    max_incre_m: 0.03
    max_incre_rad: 0.1
    max_incre_joint_rad: 0.0628
    safe_zone: [-0.5, 0.7, -0.9, -0.2, 0.2, 0.8]

ati_netft0:
    ip_address: "192.168.2.102"
    counts_per_force: 1000000
    counts_per_torque: 1000000
    sensor_name: "netft0"
    print_flag: false
    fullpath: "/tmp/netft0_data.txt"
    publish_rate: 7000
    noise_level: 0.0
    stall_threshold: 100
    Foffset: [1.88304, -15.861, 11.4758]
    Toffset: [0.576757, 0.054351, -0.0933367]
    Gravity: [-0.0512774, 0.0304736, -0.804662]
    Pcom: [0.000241627, 0.000264568, 0.0835715]
    WrenchSafety: [40.0, 40.0, 60.0, 3, 3, 3]
    PoseSensorTool: [0, 0, -0.079, -0.25882,  0,  0,  0.9659258]

coinft0:
    port: "/dev/ttyACM0"
    baud_rate: 115200
    left_calibration_file: "/shared_local/configs/coinft/UFT3_MLP_4L_scl_1_30.onnx"
    right_calibration_file: "/shared_local/configs/coinft/UFT3_MLP_4L_scl_1_30.onnx"
    noise_level: 0.0
    stall_threshold: 100
    Foffset: [0, 0, 0]
    Toffset: [0, 0, 0]
    Gravity: [0, 0, 0]
    Pcom: [0, 0, 0]
    WrenchSafety: [15.0, 15.0, 15.0, 1, 1, 1]
    PoseSensorToolLeft: [0.2, -0.086, 0, 0.5, -0.5, -0.5,  0.5]
    PoseSensorToolRight: [0.2, -0.086, 0, 0.5, -0.5, -0.5,  0.5]

gopro0:
  device_name: "/dev/v4l/by-id/usb-Elgato_Elgato_HD60_X_A00XB320216MTR-video-index0"
  frame_width: 1920
  frame_height: 1080
  crop_rows: [0, 1080] # set to negative to disable cropping
  # crop_cols: [420, 1500]
  crop_cols: [238, 1682]
  fps: 60

wsg_gripper0:
  robot_ip: "192.168.2.111"
  port: "1000"
  velResControl_kp: 3.0
  velResControl_kf: 20.0
  PDControl_kp: 10.0
  PDControl_kd: 0.001
  js_interface_config:
    num_joints: 1
    range_safety_mode: "SAFETY_MODE_TRUNCATE"
    incre_safety_mode: "SAFETY_MODE_TRUNCATE"
    max_incre: 110.0 # mm
    safe_zone: [-1, 110] # mm

admittance_controller0:
  dt: 0.002
  log_to_file: false
  log_file_path: "/tmp/admittance0_controller.log"
  alert_overrun: false
  compliance6d:
    stiffness: [200, 200, 300, 2, 2, 2] 
    damping: [15, 15, 15, 0.3, 0.3, 0.3]
    inertia: [0.2, 0.2, 0.2, 0.001, 0.001, 0.001]
    stiction: [0, 0, 0, 0, 0, 0]
  max_spring_force_magnitude: 50
  max_spring_torque_magnitude: 4
  direct_force_control_gains:
    P_trans: 0
    I_trans: 0
    D_trans: 0
    P_rot: 0
    I_rot: 0
    D_rot: 0
  direct_force_control_I_limit: [0, 0, 0, 0, 0, 0]


perturbation_generator0:
  force_magnitude: 1.0
  force_stddev: 5
  torque_magnitude: 1.5
  torque_stddev: 0.1
  perturbation_duration_ms: 100
  interval_duration_ms: 100
  interval_stddev: 100
  magnitude_type: "CONSTANT"
  duration_type: "CONSTANT"