# Inference
#    plot_rgb: false
#    damping: high damping
#    max_spring_force_magnitude: 50
# Data collection:
#    plot_rgb: true
#    damping: low damping
#    max_spring_force_magnitude: 15
# always check the first few parameters:
data_folder: "/home/zhanyi/"
mock_hardware: false
bimanual: false
use_perturbation_generator: false

run_robot_thread: true
run_eoat_thread: false
run_wrench_thread: true
run_rgb_thread: true
run_key_thread: false
plot_rgb: true

rgb_buffer_size: 11
robot_buffer_size: 100
eoat_buffer_size: 100
wrench_buffer_size: 1000
camera_selection: "OAK"
force_sensing_mode: "FORCE_MODE_ATI"
compliance_control_force_source: "UR"
low_damping: [2.0, 2.0, 2.0, 0.05, 0.05, 0.05]
output_rgb_hw: [224, 224]
wrench_filter_parameters: [5, 0.002, 5] # cutoff frequency, sampling time, order
check_robot_loop_overrun: false

ur_rtde0:
  robot_ip: "192.168.2.105"
  rtde_frequency: 500.0
  rt_receive_priority: 90
  rt_control_priority: 85
  interface_priority: 80
  linear_vel: 0.5
  linear_acc: 0.5
  servoL_lookahead_time: 0.1
  servoL_gain: 600
  robot_interface_config:
    zone_safety_mode: "SAFETY_MODE_TRUNCATE"
    incre_safety_mode: "SAFETY_MODE_STOP"
    operation_mode: "OPERATION_MODE_CARTESIAN"
    max_incre_m: 0.03
    max_incre_rad: 0.2
    max_incre_joint_rad: 0.0628
    safe_zone: [-0.5, 0.7, -0.25, 0.9, 0.2, 0.8]

ati_netft0:
  ip_address: "192.168.2.101"
  counts_per_force: 1000000
  counts_per_torque: 1000000
  sensor_name: "netft0"
  print_flag: false
  fullpath: "/tmp/netft0_data.txt"
  publish_rate: 500
  noise_level: 0.0
  stall_threshold: 100
  Foffset: [12.6831, 9.53007, 11.5014]
  Toffset: [0.368655, -0.494696, -0.151527]
  Gravity: [-0.623601, 0.254525, -14.7879]
  Pcom: [0.00174549, 0.00228855, 0.0605125]
  # Foffset: [13.7324, 10.6306, 9.2794]
  # Toffset: [-0.0679116, 0.0648527, -0.0906809]
  # Gravity: [-0.0191099, 0.0209755, -1.40742]
  # Pcom: [0.000768952, 0.00617584, 0.0839475]
  WrenchSafety: [60.0, 60.0, 80.0, 4, 4, 4]
  # PoseSensorTool: [0.00, 0, -0.045, 0.7071, 0., 0., 0.7071] # new blade, assuming tcp is at 50mm
  PoseSensorTool: [0.00, 0, -0.005, 0.7071, 0., 0., 0.7071] # new blade, assuming tcp is at 50mm

gopro0:
  # device_name: "/dev/video1"
  device_name: "/dev/v4l/by-id/usb-Elgato_Elgato_HD60_X_A00XB320216NRW-video-index0"
  # device_name: "/dev/v4l/by-id/usb-Elgato_Elgato_HD60_X_A00XB320216MTR-video-index0" # right arm
  frame_width: 1920
  frame_height: 1080
  crop_rows: [0, 1080] # set to negative to disable cropping
  crop_cols: [420, 1500]
  fps: 60
  cv_num_threads: 8

oak0:
  frame_width: 1280
  frame_height: 800
  crop_rows: [-1, -1] # set to negative to disable cropping
  crop_cols: [-1, -1]
  fps: 60
  cv_num_threads: 8
  exposure_time: 1500 # 2500
  iso: 350

admittance_controller0:
  dt: 0.002
  log_to_file: false
  log_file_path: "/tmp/admittance0_controller.log"
  alert_overrun: false
  compliance6d:
    stiffness: [500, 500, 800, 0.8, 0.8, 0.3] 
    # stiffness: [200, 200, 300, 0.3, 0.3, 0.3] 
    damping: [5.1, 5.1, 5.1, 0.15, 0.15, 0.15] # for data collection
    inertia: [0.6, 0.6, 0.6, 0.02, 0.02, 0.02]
    # inertia: [0.1, 0.1, 0.1, 0.001, 0.001, 0.001]
    stiction: [0, 0, 0, 0, 0, 0]
  max_spring_force_magnitude: 10
  max_spring_torque_magnitude: 1
  direct_force_control_gains:
    P_trans: 0
    I_trans: 0
    D_trans: 0
    P_rot: 0
    I_rot: 0
    D_rot: 0
  direct_force_control_I_limit: [0, 0, 0, 0, 0, 0]

perturbation_generator0:
  force_magnitude: 2.0
  force_stddev: 1.0
  torque_magnitude: 1.5
  torque_stddev: 1.5
  perturbation_duration_ms: 80
  interval_duration_ms: 50
  interval_stddev: 100
  magnitude_type: "CONSTANT" # "CONSTANT"
  duration_type: "CONSTANT"
