# Inference
#    plot_rgb: false
#    damping: high damping
#    max_spring_force_magnitude: 50
# Data collection:
#    plot_rgb: true
#    damping: low damping
#    max_spring_force_magnitude: 15
# always check the first few parameters:
data_folder: "/home/xuxm/data/real/demonstration"
mock_hardware: false
bimanual: false
use_perturbation_generator: true

run_robot_thread: true
run_eoat_thread: false
run_wrench_thread: true
run_rgb_thread: true
plot_rgb: true
run_data_saving_thread: false

rgb_buffer_size: 11
robot_buffer_size: 600
eoat_buffer_size: 100
wrench_buffer_size: 8000
camera_selection: "GOPRO"
force_sensing_mode: "FORCE_MODE_ATI"
low_damping: [2.0, 2.0, 2.0, 0.1, 0.1, 0.1]
output_rgb_hw: [224, 224]
wrench_filter_parameters: [5, 0.000143, 5] # cutoff frequency, sampling time, order

ur_rtde0:
  robot_ip: "192.168.2.105"
  rtde_frequency: 500.0
  rt_receive_priority: 90
  rt_control_priority: 85
  interface_priority: 80
  linear_vel: 0.5
  linear_acc: 0.5
  servoL_lookahead_time: 0.1
  servoL_gain: 600
  robot_interface_config:
    zone_safety_mode: "SAFETY_MODE_TRUNCATE"
    incre_safety_mode: "SAFETY_MODE_STOP"
    operation_mode: "OPERATION_MODE_CARTESIAN"
    max_incre_m: 0.03
    max_incre_rad: 0.2
    max_incre_joint_rad: 0.0628
    safe_zone: [-0.5, 0.7, -0.05, 0.9, 0.2, 0.8]

ati_netft0:
    ip_address: "192.168.2.101"
    counts_per_force: 1000000
    counts_per_torque: 1000000
    sensor_name: "netft0"
    print_flag: false
    fullpath: "/tmp/netft0_data.txt"
    publish_rate: 7000
    noise_level: 0.0
    stall_threshold: 100
    Foffset: [2.35782, -16.7001, 10.9528]
    Toffset: [0.621768, 0.0907079, -0.0919309]
    Gravity: [-0.0186664, -0.0207649, -0.916754]
    Pcom: [-1.17041e-05, -0.000307188, 0.0840279]
    WrenchSafety: [40.0, 40.0, 60.0, 3, 3, 3]
    PoseSensorTool: [0, 0, -0.079, -0.25882,  0,  0,  0.9659258]

gopro0:
  # device_name: "/dev/video1"
  device_name: "/dev/v4l/by-id/usb-Elgato_Elgato_HD60_X_A00XB320216NRW-video-index0"
  # device_name: "/dev/v4l/by-id/usb-Elgato_Elgato_HD60_X_A00XB320216MTR-video-index0" # right arm
  frame_width: 1920
  frame_height: 1080
  crop_rows: [0, 1080] # set to negative to disable cropping
  crop_cols: [420, 1500]
  fps: 60

admittance_controller0:
  dt: 0.002
  log_to_file: false
  log_file_path: "/tmp/admittance0_controller.log"
  compliance6d:
    stiffness: [200, 200, 300, 2, 2, 2] 
    damping: [3.1, 3.1, 3.1, 0.3, 0.3, 0.3] # for data collection
    inertia: [0.1, 0.1, 0.1, 0.001, 0.001, 0.001]
    stiction: [0, 0, 0, 0, 0, 0]
  max_spring_force_magnitude: 15
  direct_force_control_gains:
    P_trans: 0.5
    I_trans: 0
    D_trans: 0
    P_rot: 0.5
    I_rot: 0
    D_rot: 0
  direct_force_control_I_limit: [0, 0, 0, 0, 0, 0]

perturbation_generator0:
  force_magnitude: 2.0
  force_stddev: 1.0
  torque_magnitude: 1.5
  torque_stddev: 1.5
  perturbation_duration_ms: 80
  interval_duration_ms: 50
  interval_stddev: 100
  magnitude_type: "CONSTANT" # "CONSTANT"
  duration_type: "CONSTANT"
